version = 1

exclude_patterns = ["proto/**"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_root = "github.com/mongorpc/mongorpc"

[[transformers]]
name = "gofmt"
enabled = true
